name: codehost

services:
  # --- Core Infrastructure ---
  postgres:
    image: postgres:15-alpine
    container_name: codehost-db
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASS:-pass}
      POSTGRES_DB: ${DB_NAME:-codehost}
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  redis:
    image: redis:7-alpine
    container_name: codehost-redis
    volumes:
      - ../data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  # --- CodeHost Services ---
  api:
    image: ghcr.io/arsh-pathan/codehost-api:latest
    container_name: codehost-api
    user: "${PUID}:${PGID}"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PORT: 4000
      DATABASE_URL: postgresql://${DB_USER:-codehost}:${DB_PASS:-securepass}@postgres:5432/${DB_NAME:-codehost}?schema=public
      REDIS_URL: redis://redis:6379
      VIRTUAL_HOST: api.code-host.online
      VIRTUAL_PORT: 4000
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: api.code-host.online
      LETSENCRYPT_EMAIL: admin@code-host.online
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "../data/api_tmp:/app/tmp"
    restart: unless-stopped
    networks:
      - default
      - proxy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  web:
    image: ghcr.io/arsh-pathan/codehost-web:latest
    container_name: codehost-web
    user: "${PUID}:${PGID}"
    depends_on:
      - api
    environment:
      NODE_ENV: production
      HOSTNAME: "0.0.0.0"
      PORT: 3000
      NEXT_PUBLIC_API_URL: ${API_URL:-https://api.code-host.online}
      VIRTUAL_HOST: code-host.online,www.code-host.online
      VIRTUAL_PORT: 3000
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: code-host.online,www.code-host.online
      LETSENCRYPT_EMAIL: admin@code-host.online
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - default
      - proxy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

networks:
  proxy:
    external: true
